Repository ember-bootstrap/ember-bootstrap-cp-validations, pull requests merged in 2020-09, with the labels that each got.

#29 Setup release-it
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#34 Support ember-bootstrap v4 and ember-cp-validations v4, drop support for older versions
  README.md
  addon/components/bs-form.js
  addon/components/bs-form/element.js
  ember-cli-build.js
  package.json
  tests/integration/components/bs-form-element-test.js
  yarn.lock
Labels: breaking, enhancement

#30 Setup dependabot
  .dependabot/config.yml
Labels: internal

#36 Yarn upgrade
  yarn.lock
Labels: dependencies

#38 Verify model exists before testing a validator exists
  addon/components/bs-form.js
  tests/integration/components/bs-form-element-test.js
Labels: bug

#25 Move CI to Github Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: internal
